from . import res_config_settings
from . import product
from . import sale_order
from . import product_tag
from . import company
from . import warehouse
from . import res_partner
from . import stock_picking_batch
from . import stock_picking_type
from . import goflow_sync_index
